name: GitOps Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Récupération du dépôt
        uses: actions/checkout@v4

      - name: Afficher l'intention
        run: |
          echo "Contenu du fichier intent.yml :"
          cat intent.yml

      - name: Réconciliation (GitOps controller)
        run: |
          chmod +x reconcile.sh
          ./reconcile.sh

      - name: Vérification du résultat
        run: |
          echo "Site généré :"
          cat index.html

      - name: Préparation de GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload du site
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Déploiement
        id: deployment
        uses: actions/deploy-pages@v4
